### ISSUE TITLE
Can this code is production useable ?

### ISSUE THREAD

**Issue by Sanath91009** [tonyroberts/generator_tools#1]
Hi,

I have a usecase where I need to persist the generator object and resume the execution when the endpoint is called again. What do you think of following this approach ?

Thanks.

**Comment by tonyroberts** [comment]
No, this fork is specifically for Python 2.7 and won't work with more modern Python versions. If you need to use this for Python 3 you would need for fork this (or the parent repo) and make any necessary changes, but as it is right now, this repo won't work unless you're using Python 2.7.
